-- ---------------------------------------------------------------------------
-- A CODE PER CONSULTANT, typed by the student at sign-up.
--
-- Invite links already enrol a student with the consultant who sent them, but
-- a link has to be sent to one person. A code can be said on the phone,
-- printed on a flyer or put in a WhatsApp status: SNZ-HIN482. A student who
-- types it at sign-up (or later, in Settings) is assigned to that consultant,
-- and every list can then say who brought them.
--
-- Generated by the database, for every staff account, so nobody has to
-- remember to make one: existing staff get theirs now, new ones on creation.
-- Three letters of the name plus three digits; retried until unique.
-- ---------------------------------------------------------------------------

ALTER TABLE users ADD COLUMN IF NOT EXISTS consultant_code TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS users_consultant_code_key
  ON users (upper(consultant_code)) WHERE consultant_code IS NOT NULL;

CREATE OR REPLACE FUNCTION new_consultant_code(person_name TEXT) RETURNS TEXT AS $$
DECLARE
  stem TEXT := upper(left(regexp_replace(coalesce(person_name, ''), '[^A-Za-z]', '', 'g'), 3));
  candidate TEXT;
BEGIN
  IF length(stem) < 3 THEN stem := rpad(stem, 3, 'X'); END IF;
  LOOP
    candidate := 'SNZ-' || stem || lpad((floor(random() * 900) + 100)::int::text, 3, '0');
    EXIT WHEN NOT EXISTS (SELECT 1 FROM users WHERE upper(consultant_code) = candidate);
  END LOOP;
  RETURN candidate;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION assign_consultant_code() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.consultant_code IS NULL AND NEW.role IN ('advisor', 'admin', 'super_admin') THEN
    NEW.consultant_code := new_consultant_code(NEW.name);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_consultant_code_trigger ON users;
CREATE TRIGGER users_consultant_code_trigger
  BEFORE INSERT OR UPDATE OF role ON users
  FOR EACH ROW EXECUTE FUNCTION assign_consultant_code();

-- Existing staff, one at a time so each sees the codes already given.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN SELECT id, name FROM users
           WHERE role IN ('advisor', 'admin', 'super_admin') AND consultant_code IS NULL LOOP
    UPDATE users SET consultant_code = new_consultant_code(r.name) WHERE id = r.id;
  END LOOP;
END
$$;
